### ISSUE TITLE
GC3 200 and earlier: Thermal Padding color blending issues

### ISSUE THREAD

**Issue by radfast** [micdoodle8/Galacticraft#1048]
Two issues with the Thermal Padding, most easily seen on Mars.

1.  Thermal Padding items, picking up the dimension's color and partially transparent:
![2014-09-24_15 32 36](https://cloud.githubusercontent.com/assets/6842258/4390163/fe031f38-43fa-11e4-8ed0-6524edcbf2e3.png)

2.  Thermal Padding worn by the player is affected by the dimension's overall color (SkyColor?  FogColor? I'm not sure), for example it's too orange on Mars.

**Comment by Korynkai** [comment]
Oh, didn't see this when I posted #1429, but, as a rendering issue, these two are related.

**Comment by EzerArch** [comment]
> Thermal Padding items, picking up the dimension's color and partially transparent

Fixed.

> Thermal Padding worn by the player is affected by the dimension's overall color (SkyColor? FogColor? I'm not sure), for example it's too orange on Mars.

Certainly fixed.

> Rendering a player equipped with Thermal Leggings but no Thermal Chestpiece, he is rendered with a partial Thermal Chestpiece also. Same for Thermal Boots, gives partial Thermal Leggings.

Because this is how armor graphics work. Minecraft uses part of chest plate in <material>_layer_1.png as suspenders/braces for leggings. If you want to avoid that, GC will need a thermalPadding_2.png and blank the undesirable pixels in thermalPadding_1.png.

I think this issue can be closed. I'll open another one about a new bug I've just found related to Thermal Padding.

**Comment by radfast** [comment]
There's still an issue where an enchanted item is in the next slot to a Thermal Armor item.  But I have a better understanding of OpenGL blend functions now since I opened this issue, so maybe I can find a fix :)

**Comment by radfast** [comment]
Holy moly, @EzerArch - that's some impressive testing.

The next version will, I hope, fix all of the different issues which are connected with a Thermal Padding item being in the player inventory - but when .303 comes out, please do feel free to test those things and see if you agree :)

This will not fix the "Warning: Oxygen Setup is Invalid" issue, but it's pointing the way ...

I am going to treat the leggings = partial chest issue (my original issue 3) as 'Not a Galacticraft Issue'.

**Comment by micdoodle8** [comment]
2 is fixed as of 6fa32a1b299a67fb7776c0dd348b05ccdfe9457c, 6 is fixed in the Galacticraft extended inventory, can't do anything about that in the regular inventory screens of course.

**Comment by radfast** [comment]
I can reproduce 6 with the Galacticraft tab (+ an active potion effect) only if my mouse picks up a Nether Star while the Galacticraft tab is open.

I think 4 is fixed in the situation I just described.

I cannot test 5 as I don't have a cape. :(
