### ISSUE TITLE
Leave bed button in a Cryogenic Chamber doesn't work

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1159]
If you sleep in a Cryogenic Chamber on night time or day time. When I press the leave bed button that doesn't work.

**Comment by EzerArch** [comment]
I attempted to use the cryogenic chamber in 431. This is what happens:
1. right-click to use
2. the game teleports you inside the chamber, but with normal bed-sleeping position (pic 1).
3. when you are about to wake up, the game teleports 1 block up (pic 2).
4.you wake up facing to the opposite direction with your head sticking out of the chamber. (pic 3, 4).

![1](https://cloud.githubusercontent.com/assets/6743303/12930919/348db70e-cf62-11e5-9ec8-edb2ffd2a5e1.png)
![2](https://cloud.githubusercontent.com/assets/6743303/12930920/34964860-cf62-11e5-992c-ff6cceaf7785.png)
![2016-02-09_19 28 24](https://cloud.githubusercontent.com/assets/6743303/12931206/ab162662-cf63-11e5-8b50-5d4d784cceb0.png)
![2016-02-09_19 34 39](https://cloud.githubusercontent.com/assets/6743303/12931304/36c14930-cf64-11e5-8ed0-90ef2a8565fc.png)

I'm also investigating other issues when installed with mods other than those listed below. For example: once the player awakens, the cryochamber becomes impassable and the player has to break free.

**Mods used:**
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
Galacticraft-Planets-1.7-3.0.12.441.jar
GalacticraftCore-1.7-3.0.12.441.jar
MicdoodleCore-1.7-3.0.12.441.jar
OptiFine_1.7.10_HD_U_D1.jar (with and without)

**Comment by EzerArch** [comment]
Tried to reproduce: no longer happens in 466.

**Comment by radfast** [comment]
Thank you :)   This one is so hard to get right.  Your careful testing really helps :)

**Comment by radfast** [comment]
This should all be fixed in latest build 492 for 1.7.10.

Also fixed in Galacticraft 4 beta.  (But not tested there with SmartMoving... yet!)

**Comment by idkw** [comment]
Hello,
Sorry for the necro but this bug is still present in GalacticraftCore-1.12.2-4.0.2.231.jar
When the cryogenic Chamber is placed into a wall, the leave bed button doesn't work

![image](https://user-images.githubusercontent.com/7012331/63039097-dbad2080-bec2-11e9-883d-bf3cf9028c23.png)

Thanks
