### ISSUE TITLE
NEI slight darkening of items with Galacticraft inventory open

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#1532]
When I press the Galacticraft tab on my inventory, all the *vanilla* items on NEI become darker.
So weird!
Tested with build 306

**Comment by radfast** [comment]
Duplicate of #1524, but as that one is closed but the issue is still happening, it's still an issue ...

**Comment by radfast** [comment]
This is an __extremely weird__ issue.
* It's intermittent.
* You can __cancel__ the darkening by having a mob spawner item show on screen (e.g. search for one in NEI)
* After you have cancelled the darkening by having a mob spawner show, __it never happens again that game__ even if the mob spawner is removed

**Comment by micdoodle8** [comment]
Should be fixed after 1131fd6877685d1901e821c8be98f3f64032e2af, which will be in the next build. If not, please re-open this issue.

**Comment by radfast** [comment]
xJon reporting that this is still happening in build .334, see #1639.

I'm not at a gaming PC just now, can't test this until later.

**Comment by XFactHD** [comment]
I don't think that this is a bug in the galacticraft tab because many other mods have the same problem. If you hover over the fluids in a tcon smeltery, then you have the same thing. I think it has something to do with how NEI handles custom inventories and GUIs.

**Comment by xJon** [comment]
@XFactHD That's not true. The bug you're talking about is indeed a *bug* in TiC, and not in NEI, same for here. Also you can see they tried to fix it and it's coming back.

**Comment by radfast** [comment]
Calm down please @xJon.

The issue is related to NEI not explicitly setting one of the OpenGL lighting settings which it needs for its item display.  __Something__ on-screen when the Galacticraft inventory is shown is using the lighting setting, which messes up NEI.  What that "thing" is, and whether it is in Galacticraft or only because the Galacticraft inventory tab draws the player, is currently unknown.  In my tests, I currently cannot reproduce this issue, so it may be that it is not in Galacticraft at all, but something your player is wearing or holding.  But, in past testing I have noticed the issue is intermittent, and seems to depend on what has been rendered in the past (a mob spawner, as mentioned).

If you can do some more testing to give me exact steps on how to see this, that would be very helpful.  For a start
* does the issue happen if you have no other mods installed except Galacticraft and NEI - please check carefully all other mods are gone, for example _Baubles_ can be hiding in your ```mods/1.7.10``` folder?
* does it happen on a fresh start of the game, so the player is wearing no armor and holding no item, and has no Galacticraft equipment?

**Comment by xJon** [comment]
@radfast I'm totally calm, lol :P
I will do some testing, understandable.

**Comment by radfast** [comment]
OK, on more testing, I am seeing the issue, but only sometimes, it depends what is shown in NEI.

* If a NASA Workbench or a Sludgeling Spawner is in NEI, then any blocks drawn after that item have the correct brightness.  Try a NEI search for "w" or "ch" to see this.
* If a __Slimeling Spawner__ was on your NEI screen at any time, that magically fixes the issue for all the rest of that game session until you restart your Minecraft client.

Specific information like this may help to track it down.

**Comment by xJon** [comment]
This issue happens YET AGAIN with build 341.
VERY SLIGHT change, but there's one. Figured I should report it.
- http://i.imgur.com/ofv2tAR.png
- http://i.imgur.com/TyXtUCQ.png

**Comment by radfast** [comment]
Please post a comparable screenshot of your main inventory, not Tinkers Construct tab.

**Comment by xJon** [comment]
@radfast 
- http://i.imgur.com/5xho9hc.png
- http://i.imgur.com/EJF1d2y.png

**Comment by xJon** [comment]
@radfast Did the pictures I posted are okay?

**Comment by radfast** [comment]
Yes.  Which MC version are you using, and do you have Optifine (if so which version)?

**Comment by xJon** [comment]
@radfast 1.7.10. No optifine. :)

**Comment by xJon** [comment]
@radfast Anything new? Thanks.

**Comment by xJon** [comment]
https://github.com/micdoodle8/Galacticraft/pull/1926
This fixed it ^
Thanks.
