### ISSUE TITLE
AE2 Meteorite World Generation Not Whitelisting

### ISSUE THREAD

**Issue by Xanarios** [micdoodle8/Galacticraft#1547]
With at least Galacticraft 3.0.11.306 and Applied Energistics 2 RV2.Beta.24, AE2 meteorites are no longer generating in various Galacticraft dimensions.  It seems the AE2 MeteoriteWorldGen class has been moved in recent commits.

From [micdoodle8.mods.galacticraft.core.util.WorldUtil] (https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L1159):
```javascript
Class ae2meteorPlace = Class.forName("appeng.hooks.MeteoriteWorldGen");
```

Should probably point to [appeng.worldgen.MeteoriteWorldGen] (https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/main/java/appeng/worldgen/MeteoriteWorldGen.java) instead.

**Comment by micdoodle8** [comment]
Okay, there's a new build with an attempted fix now. This should fix the issue, but please re-open if not.

**Comment by almightyfoon** [comment]
As of version 3.0.12.357 this is still an issue. I've got the moon and asteroid dimensions in the AE2 whitelist and ran around with the meteor compass for a while and it didn't find anything.

using AE2 RV2 stable 10
