### ISSUE TITLE
Mod/recipe conflict w/Actually Additions (tiny coal)

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2859]
Galacticraft-Planets 1.10.2-4.0.0.107
GalacticraftCore 1.10.2.4.0.0.99
MiccdoodleCore 1.10.2-4.0.0.107

Galacticraft-Planets 1.11.2-4.0.0.106
GalacticraftCore 1.11.2-4.0.0.106
MiccdoodleCore 1.11.2-4.0.0.106

The conflict is with tiny coal, 1 coal = 8 tiny coal. 1 tiny coal will smelt 1 item in vanilla furnace or make tiny torch. So I can't make fragmented carbon.

**Comment by radfast** [comment]
Should we:
(A)  accept Tiny Coal as an alternative to Fragmented Carbon
(B)  offer a recipe where 1 tiny coal makes 1 Fragmented Carbon?

**Comment by TheQuadShot** [comment]
No, they have tiny charcoal as well. I think you should accept coal/charcoal powder as an alternative for fragmented carbon, and there are a few mods that let you make(and use) the powder. Actually Additions will make coal/charcoal powder in their crusher.

**Comment by TheQuadShot** [comment]
I've been thinking about this... What if you made it a Compressor recipe? imho it would be better for the mod than taking something from another mod. Else you could make it a shaped recipe (2 coal/charcoal = x Fragmented carbon)

**Comment by radfast** [comment]
I've added new shapeless recipes for 4 Coal -> 32 Fragmented Carbon.

I think that should fix it, it doesn't look like AA has any similar recipe (I guess it's possible that another mod could... ... let's hope not).

I am reluctant to add a Compressor recipe because there is already a Compressed Steel recipe incorporating coal, and I wouldn't want some other recipe to start running if the player is placing coal on the crafting grid in preparation to making steel.

There is also (and has been for a long time) a Charcoal -> Fragmented Carbon recipe.  And if all else fails, Fragmented Carbon is now found as a bulk / filler item in Mars dungeon chests, that's another recent change.

**Comment by TheQuadShot** [comment]
This bug is back in build .174 and probably earlier builds, but I just noticed it trying to make some tiny coal on a new map. The 4 (2_x_2) recipe works, but 1 coal=8 Fragmented Carbon is the problem.

**Comment by radfast** [comment]
I don't understand?  The 4 Coal -> 32 Fragmented Carbon is the intended solution to this issue.  We can't stop another mod making its recipe for 1 Coal.

**Comment by TheQuadShot** [comment]
In AA 1 coal/charcoal = 8 tiny coal/charcoal, but I'm getting 8 fragmented carbon, not tiny coal.
I think the problem is line 93 https://github.com/micdoodle8/Galacticraft/commit/4bb3bdd0468bb889afba881261478fcf9e735eb7
