### ISSUE TITLE
Wrong Status on Electric Compressor and Cirtuit Fabricator when redstone signal nearby

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3310]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.168

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.
- Status _Idle_ instead _OFF_ 
![2018-04-02_23 01 00](https://user-images.githubusercontent.com/36822613/38217328-4731084a-36ce-11e8-9b60-b39a873051f9.png)
![2018-04-02_23 01 18](https://user-images.githubusercontent.com/36822613/38217338-4e9c2cf4-36ce-11e8-8e82-d99e2ce4cb90.png)

- Can _Oxygen Sealer_ be disabled by redstone signal?
![2018-04-02_23 31 53](https://user-images.githubusercontent.com/36822613/38217418-94e78316-36ce-11e8-9d9b-11fb8393a891.png)

**Comment by TheQuadShot** [comment]
I'm not exactly sure what you mean, however I am sure that it is related to this issue:
https://github.com/micdoodle8/Galacticraft/issues/2850
You should search the database for "is:issue" and don't a use "is:open" or "is:closed"

**Comment by radfast** [comment]
All or almost all electrically powered machines in Galacticraft can be disabled by redstone signals.

I agree that the Electric Compressor and Circuit Fabricator should read "OFF".

**Comment by radfast** [comment]
Should be fixed in next build 169.

**Comment by radfast** [comment]
Build 169 is now available to download.

**Comment by FrostQ** [comment]
Cirtuit Fabricator's status still don't read "OFF" and "idle" is in wrong location if have no energy (or no redstone signal on this screen)
![2018-04-07_13 40 18](https://user-images.githubusercontent.com/36822613/38454547-9b518dca-3a69-11e8-860e-2b40e34905db.png)
![2018-04-07_13 40 41](https://user-images.githubusercontent.com/36822613/38454550-ab9afee6-3a69-11e8-866f-7505e327483c.png)

**Comment by TheQuadShot** [comment]
intended behavior, as the machine is never "off" it only has the 2 states(idle and running), and an "off" state would not consume power, which is not the case. This should actually be filed as an inconsistency in behavior as the other machines give the status of "no power"

**Comment by radfast** [comment]
Fixed properly in next build, thanks guys.
