### ISSUE TITLE
Launch Controller-guided rocket don't stop play sound after landing

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3383]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.175

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

Rocket sound don't stop after Launch Controller-guided rocket is landed

**Comment by radfast** [comment]
More explanation please.  I can't reproduce this in testing.

1.  Is it happening every time for you / only once / sometimes but not always?

2. What type of rocket? 

3.  Which dimension are you landing in?  (Same as launch dimension or different?)

4.  Are you 100% certain the rocket landed and switched off engines?

**Comment by QuantumStatement** [comment]
1. It's happening sometimes but not always
2. I tested Cargo Rocket and Tier 2 Rocket
3. I'm landen on Space Station from Overworld and vice versa
4. Yes

I think it may be sound doubling

**Comment by AGuyNamedJens** [comment]
I actually have the same issue right now.
Tier 3 rocket, automated schedule to space station & back to earth
When i'm in it it won't stop playing the sound when it landed, sometimes this happends on automated routes without me in it also..

**Comment by QuantumStatement** [comment]
Looks like it's fixed in 5acfaf56b48edc88ff2741d052bdb0ffcd532849

**Comment by EzerArch** [comment]
@radfast or @micdoodle8 , you might want to close this.

**Comment by AGuyNamedJens** [comment]
@QuantumStatement how do i install that version? Latest which i installed today doesn't fix it, so imma assume it's not published yet

**Comment by EzerArch** [comment]
> how do i install that version?

The fix is not out yet.

> Thanks, should be fixed in the next build (https://github.com/micdoodle8/Galacticraft/issues/3944#issuecomment-617084639)
