### ISSUE TITLE
GC itens from furnace can't be removed

### ISSUE THREAD

**Issue by RenanVieira88** [micdoodle8/Galacticraft#3590]
**Minecraft version: 1.12.2

Galacticraft version:
GalacticraftCore-1.12.2-4.0.1.181
Galacticraft-Planets-1.12.2-4.0.1.181
MicdoodleCore-1.12.2-4.0.1.181

SMP/SP : Multiplayer (SMP)

Addons: Extra planets - planet progression**

When use Craftteakers command "furnace.removeAll();" GC ores still able to make itens in furnace
Exemple: Vanilla iron ore can't do ingots, but GC ores can

https://pastebin.com/smuAY2nm

**Comment by MJRLegends** [comment]
probably already fixed by https://github.com/micdoodle8/Galacticraft/pull/3578 just need to wait in till the devs update the mod.

**Comment by EngineerXL** [comment]
Same as [#3514](https://github.com/micdoodle8/Galacticraft/issues/3514)

**Comment by micdoodle8** [comment]
Should be fixed in build 185+

**Comment by RenanVieira88** [comment]
Tnks for fast respond, the most itens be removed, only 2 still not removing, crushed aluminium and purifed
![54](https://user-images.githubusercontent.com/24437327/50864399-10835300-1389-11e9-8ede-c59194d65da9.png)

**Comment by MJRLegends** [comment]
crushed aluminium core isn't added by GC i dont think

**Comment by RenanVieira88** [comment]
Ic2 maybe?
