### ISSUE TITLE
Broken Electric Arc Furnace, world becomes inaccessible after placing down

### ISSUE THREAD

**Issue by VictorGamerLOL** [micdoodle8/Galacticraft#3736]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.215

Single player (SSP)

no add-ons

When I place down Electric Arc Furnace the game crashes and the world can't be accessed anymore. Here is crash report (WARNING: I am using 65 mods): 
[crash-2019-07-24_12.35.35-server.txt](https://github.com/micdoodle8/Galacticraft/files/3426622/crash-2019-07-24_12.35.35-server.txt)

The game does start, but the world becomes corrupted and inaccessible. I have to remove the mod to get the world back

**Comment by micdoodle8** [comment]
Thanks, fixed as of build 218

**Comment by Vliro** [comment]
@micdoodle8 I am using 218 and while the world isn't unusable it still crashes and have to be restarted.

https://pastebin.com/RfjqYRiX

**Comment by BlueMagma2** [comment]
@micdoodle8 : 

I am using version GalacticraftCore-1.12.2-4.0.2.221 and get a crash using the electric arc furnace

It used to be when trying to open the furnace interface after loading the world. the solution was to break the block and put a new one.

Now it is crashing at startup (I assume it's because the furnace was active when I exited the game last time.

Full crash stafck trace : https://pastebin.com/5V82wbvV

**Comment by MJRLegends** [comment]
Well yea you need to update lol

**Comment by micdoodle8** [comment]
@Vliro @BlueMagma2 Both issues should be fixed as of the latest build (229).

If you're using any GC addons, those should be updated as well.

**Comment by Bahrcad-71** [comment]
Hi. I was having the exact same issue.  I got the suggestion on another forum to use MCEdit to delete the placed Arc Furnace block, and it work insofar as the world loads once again.

Also, as suggested here, I replaced my Build 215 Core/McDoodle/Planets jar files with a newer build (232).  When I loaded the world the Electric Arc Furnace was in my hand and placing it did not cause a crash.  Thanks for the tips.
