### ISSUE TITLE
[BUG] Ender IO Energy Cables

### ISSUE THREAD

**Issue by Gandalf360one** [micdoodle8/Galacticraft#3809]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.237
GalaxySpace version:  1.12.2-2.0.10

EnderIO: 1.12.2-5.51.
EnderIOCore: 1.12.2-0.5.69
    Addon: GasConduits 1.12.2-1.2.2

ThermalFoundation: 1.12.2-2.6.3.27
ThermalDynamics: 1.12.2-2.5.5.21
ThermalExpansion: 1.12.2-5.5.4.43

CodeChickenLib: 1.12.2-3.2.3.358

Mekanism: 1.12.2-9.8.2.389
MekanismGenerators: 1.12.2-9.8.2.389
MekanismTools: 1.12.2-9.8.2.389

Ender-IO Energy Cables connect to the input from machines but wont connect to the output from the machines.

![batterieBox](https://user-images.githubusercontent.com/48660271/66582452-1ad5b600-eb82-11e9-8159-886aa31608cd.PNG)

So I want to know if it is possible to fix this ?

**Comment by radfast** [comment]
EnderIO version please, also please list any other EnderIO related mods.

**Comment by Gandalf360one** [comment]
Updated

**Comment by radfast** [comment]
Thank you for the clear report.

We were missing "ForgeEnergy" capability for Galacticraft power producing tiles like the Energy Storage Module.  Looks like EnderIO now uses ForgeEnergy not RF.

This should be fixed in next build .238.   I'd be grateful if you can let us know if everything looks OK to you.

**Comment by Gandalf360one** [comment]
I have tested it but the output still wont connect with the EnderIO cables

**Comment by Gandalf360one** [comment]
> 
> 
> Thank you for the clear report.
> 
> We were missing "ForgeEnergy" capability for Galacticraft power producing tiles like the Energy Storage Module. Looks like EnderIO now uses ForgeEnergy not RF.
> 
> This should be fixed in next build .238. I'd be grateful if you can let us know if everything looks OK 
to you.

It wont work. I have tested it in my modpack and also with only Galacticraft and EnderIO.
Could it be that it wont work because i use the newest forge 1.12.2 version ?

**Comment by radfast** [comment]
We'll check again with the newest Forge.

**Comment by Gandalf360one** [comment]
Any news about the fix ?

**Comment by radfast** [comment]
Not had time yet, I'm very busy with 'real life' issues.  This is an open issue near the top of our issues list, and it's clear what is not working, so don't worry it will be fixed soon.

**Comment by Gandalf360one** [comment]
Works greate! thank you very much for adding that thing!

**Comment by radfast** [comment]
I think all EnderIO issues are now fixed in latest build .254.   Any issues remaining, please comment here or start a new issue.

You can also use Galacticraft's Aluminum Wire to connect two EnderIO powered blocks (for example, Capacitor and another EnderIO machine), so players have that option.

It is **intended behaviour** that Galacticraft cables and EnderIO power conduits cannot directly connect to each other.  Use a block like Energy Storage Module or an EnderIO Capacitor if you want to join the two types of power.

**Comment by Gandalf360one** [comment]
I dont want to make you angry but I found another bug.
If you connect an EnderIO cable to the output of a machine it wont pull energy out.
![2020-04-20_10 58 45](https://user-images.githubusercontent.com/48660271/79733816-fb200700-82f5-11ea-9b8c-951932044111.png)
![2020-04-20_10 59 33](https://user-images.githubusercontent.com/48660271/79733843-070bc900-82f6-11ea-80a9-dfc5885c18f4.png)

**Comment by Gandalf360one** [comment]
It is working! Great work!
But there is a small problem with it. It wont work when Mekanism is installed too.
Galacticraft: latest version installed
Mekanism: latest version installed
