### ISSUE TITLE
Conflicting between EnderIO and this mod (advancements)

### ISSUE THREAD

**Issue by snow6326** [micdoodle8/Galacticraft#3828]
What happens:
The mod EnderIO is conflicting with this mod.
Some of advancements in the galacticraft work fine but the other not
It is not urgent but I still reported the issue I found :)
Ready like this mod~~!!

What you expected to happen:
Advancements of two mods work fine

Steps to reproduce:
Run the Minecraft with all mods loaded
Check whether there is error message of the logs
Take away the EnderIO and EnderCore mod
No error message shown again.
Affected Versions (Do not use "latest"):
EnderCore-1.12.2-0.5.73.jar
EnderIO-1.12.2-5.1.52.jar
GalacticraftCore-1.12.2-4.0.2.238.jar
Galacticraft-Planets-1.12.2-4.0.2.238.jar
MicdoodleCore-1.12.2-4.0.2.238.jar

Spigot:1.12.2
Forge:14.23.5.2848
Sponge:7.2.0 (Beta)
Minecraft version: 1.12.2

Your most recent log file where the issue was present:
[15:40:12] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement galacticraftcore:galacticraft/moon_dungeon

**Comment by radfast** [comment]
thanks for reporting!  @marcus8448  maybe one for you?  I'm not sure why EnderIO would give a parsing error in our advancements ... ?

**Comment by marcus8448** [comment]
Huh, I have no idea why that would happen, unless `GCTriggers#registerTriggers` somehow failed... It _might_ have to do with sponge. I'll do some tests soon.

**Comment by HenryLoenwind** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/5281<- there's a stack trace in the log

**Comment by radfast** [comment]
Thanks @HenryLoenwind for linking to the stack trace, that's super helpful :)

This should be fixed in next GC build .239.  Build .239 will become available in the next few days, I can't say exactly when as we have an issue with the build server currently.  I'll aim to post in this thread again when .239 is available for download.

**Comment by xJon** [comment]
Hi, any news regarding `.239` of Galacticraft?
Thanks!

**Comment by xJon** [comment]
Tested `.239` and I am still getting this error in the log:
```
[11:39:58] [Server thread/ERROR]: Parsing error loading built-in advancement galacticraftcore:galacticraft/oil
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'galacticraftcore:bucket_oil'
	at net.minecraft.util.JsonUtils.getItem(SourceFile:124) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.getItem(SourceFile:135) ~[rc.class:?]
	at net.minecraft.advancements.DisplayInfo.deserializeIcon(DisplayInfo.java:133) ~[r.class:?]
	at net.minecraft.advancements.DisplayInfo.deserialize(DisplayInfo.java:111) ~[r.class:?]
	at net.minecraft.advancements.Advancement$Builder.deserialize(SourceFile:202) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:517) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.gsonDeserialize(SourceFile:537) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1381) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1359) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1326) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.reload(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.init(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:122) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:39:58] [Server thread/ERROR]: Couldn't load advancement galacticraftcore:galacticraft/rocket_fuel: Task Advancement{parentId=galacticraftcore:galacticraft/refinery, display=net.minecraft.advancements.DisplayInfo@94508c9, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={fuel_bucket=net.minecraft.advancements.Criterion@2216beea}, requirements=[[fuel_bucket]]}
[11:39:58] [Server thread/ERROR]: Couldn't load advancement galacticraftcore:galacticraft/refinery: Task Advancement{parentId=galacticraftcore:galacticraft/oil, display=net.minecraft.advancements.DisplayInfo@779bb1b9, rewards=AdvancementRewards{experience=0, loot=[], recipes=[], function=null}, criteria={refinery=net.minecraft.advancements.Criterion@606db04e}, requirements=[[refinery]]}
```
I have disabled Galacticraft oil to not overlap with Buildcraft's.
(also relevant to https://github.com/micdoodle8/Galacticraft/issues/3837)

**Comment by marcus8448** [comment]
@xJon your above issue is not relevant to this one. I am currently looking into your issue. Meanwhile, you should still be able to play Galacticraft normally without the advancements.

**Comment by xJon** [comment]
@marcus8448 👍
